// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.12.4
// source: appix/v1/hostgroups.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateHostgroupsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateHostgroupsRequest) Reset() {
	*x = CreateHostgroupsRequest{}
	mi := &file_appix_v1_hostgroups_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHostgroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHostgroupsRequest) ProtoMessage() {}

func (x *CreateHostgroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appix_v1_hostgroups_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHostgroupsRequest.ProtoReflect.Descriptor instead.
func (*CreateHostgroupsRequest) Descriptor() ([]byte, []int) {
	return file_appix_v1_hostgroups_proto_rawDescGZIP(), []int{0}
}

type CreateHostgroupsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateHostgroupsReply) Reset() {
	*x = CreateHostgroupsReply{}
	mi := &file_appix_v1_hostgroups_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHostgroupsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHostgroupsReply) ProtoMessage() {}

func (x *CreateHostgroupsReply) ProtoReflect() protoreflect.Message {
	mi := &file_appix_v1_hostgroups_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHostgroupsReply.ProtoReflect.Descriptor instead.
func (*CreateHostgroupsReply) Descriptor() ([]byte, []int) {
	return file_appix_v1_hostgroups_proto_rawDescGZIP(), []int{1}
}

type UpdateHostgroupsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateHostgroupsRequest) Reset() {
	*x = UpdateHostgroupsRequest{}
	mi := &file_appix_v1_hostgroups_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHostgroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHostgroupsRequest) ProtoMessage() {}

func (x *UpdateHostgroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appix_v1_hostgroups_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHostgroupsRequest.ProtoReflect.Descriptor instead.
func (*UpdateHostgroupsRequest) Descriptor() ([]byte, []int) {
	return file_appix_v1_hostgroups_proto_rawDescGZIP(), []int{2}
}

type UpdateHostgroupsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateHostgroupsReply) Reset() {
	*x = UpdateHostgroupsReply{}
	mi := &file_appix_v1_hostgroups_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHostgroupsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHostgroupsReply) ProtoMessage() {}

func (x *UpdateHostgroupsReply) ProtoReflect() protoreflect.Message {
	mi := &file_appix_v1_hostgroups_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHostgroupsReply.ProtoReflect.Descriptor instead.
func (*UpdateHostgroupsReply) Descriptor() ([]byte, []int) {
	return file_appix_v1_hostgroups_proto_rawDescGZIP(), []int{3}
}

type DeleteHostgroupsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteHostgroupsRequest) Reset() {
	*x = DeleteHostgroupsRequest{}
	mi := &file_appix_v1_hostgroups_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHostgroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHostgroupsRequest) ProtoMessage() {}

func (x *DeleteHostgroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appix_v1_hostgroups_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHostgroupsRequest.ProtoReflect.Descriptor instead.
func (*DeleteHostgroupsRequest) Descriptor() ([]byte, []int) {
	return file_appix_v1_hostgroups_proto_rawDescGZIP(), []int{4}
}

type DeleteHostgroupsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteHostgroupsReply) Reset() {
	*x = DeleteHostgroupsReply{}
	mi := &file_appix_v1_hostgroups_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHostgroupsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHostgroupsReply) ProtoMessage() {}

func (x *DeleteHostgroupsReply) ProtoReflect() protoreflect.Message {
	mi := &file_appix_v1_hostgroups_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHostgroupsReply.ProtoReflect.Descriptor instead.
func (*DeleteHostgroupsReply) Descriptor() ([]byte, []int) {
	return file_appix_v1_hostgroups_proto_rawDescGZIP(), []int{5}
}

type GetHostgroupsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetHostgroupsRequest) Reset() {
	*x = GetHostgroupsRequest{}
	mi := &file_appix_v1_hostgroups_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostgroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostgroupsRequest) ProtoMessage() {}

func (x *GetHostgroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appix_v1_hostgroups_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostgroupsRequest.ProtoReflect.Descriptor instead.
func (*GetHostgroupsRequest) Descriptor() ([]byte, []int) {
	return file_appix_v1_hostgroups_proto_rawDescGZIP(), []int{6}
}

type GetHostgroupsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetHostgroupsReply) Reset() {
	*x = GetHostgroupsReply{}
	mi := &file_appix_v1_hostgroups_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostgroupsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostgroupsReply) ProtoMessage() {}

func (x *GetHostgroupsReply) ProtoReflect() protoreflect.Message {
	mi := &file_appix_v1_hostgroups_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostgroupsReply.ProtoReflect.Descriptor instead.
func (*GetHostgroupsReply) Descriptor() ([]byte, []int) {
	return file_appix_v1_hostgroups_proto_rawDescGZIP(), []int{7}
}

type ListHostgroupsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListHostgroupsRequest) Reset() {
	*x = ListHostgroupsRequest{}
	mi := &file_appix_v1_hostgroups_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHostgroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHostgroupsRequest) ProtoMessage() {}

func (x *ListHostgroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appix_v1_hostgroups_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHostgroupsRequest.ProtoReflect.Descriptor instead.
func (*ListHostgroupsRequest) Descriptor() ([]byte, []int) {
	return file_appix_v1_hostgroups_proto_rawDescGZIP(), []int{8}
}

type ListHostgroupsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListHostgroupsReply) Reset() {
	*x = ListHostgroupsReply{}
	mi := &file_appix_v1_hostgroups_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHostgroupsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHostgroupsReply) ProtoMessage() {}

func (x *ListHostgroupsReply) ProtoReflect() protoreflect.Message {
	mi := &file_appix_v1_hostgroups_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHostgroupsReply.ProtoReflect.Descriptor instead.
func (*ListHostgroupsReply) Descriptor() ([]byte, []int) {
	return file_appix_v1_hostgroups_proto_rawDescGZIP(), []int{9}
}

var File_appix_v1_hostgroups_proto protoreflect.FileDescriptor

var file_appix_v1_hostgroups_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x70, 0x69, 0x78, 0x2f, 0x76, 0x31, 0x2f, 0x68, 0x6f, 0x73, 0x74, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61, 0x70, 0x69,
	0x2e, 0x61, 0x70, 0x70, 0x69, 0x78, 0x2e, 0x76, 0x31, 0x22, 0x19, 0x0a, 0x17, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x6f,
	0x73, 0x74, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x19, 0x0a,
	0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x19, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x16, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x14, 0x0a,
	0x12, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x17, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a, 0x13,
	0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x32, 0xdd, 0x03, 0x0a, 0x0a, 0x48, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x73, 0x12, 0x5e, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x70,
	0x69, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x69, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x5e, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x70,
	0x69, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x69, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x5e, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x70,
	0x69, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x69, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x55, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x73, 0x12, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x69, 0x78, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70,
	0x70, 0x69, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x58, 0x0a, 0x0e, 0x4c, 0x69, 0x73,
	0x74, 0x48, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x23, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x61, 0x70, 0x70, 0x69, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x48,
	0x6f, 0x73, 0x74, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x69, 0x78, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x42, 0x27, 0x0a, 0x0c, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x69, 0x78,
	0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x15, 0x61, 0x70, 0x70, 0x69, 0x78, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x61, 0x70, 0x70, 0x69, 0x78, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_appix_v1_hostgroups_proto_rawDescOnce sync.Once
	file_appix_v1_hostgroups_proto_rawDescData = file_appix_v1_hostgroups_proto_rawDesc
)

func file_appix_v1_hostgroups_proto_rawDescGZIP() []byte {
	file_appix_v1_hostgroups_proto_rawDescOnce.Do(func() {
		file_appix_v1_hostgroups_proto_rawDescData = protoimpl.X.CompressGZIP(file_appix_v1_hostgroups_proto_rawDescData)
	})
	return file_appix_v1_hostgroups_proto_rawDescData
}

var file_appix_v1_hostgroups_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_appix_v1_hostgroups_proto_goTypes = []any{
	(*CreateHostgroupsRequest)(nil), // 0: api.appix.v1.CreateHostgroupsRequest
	(*CreateHostgroupsReply)(nil),   // 1: api.appix.v1.CreateHostgroupsReply
	(*UpdateHostgroupsRequest)(nil), // 2: api.appix.v1.UpdateHostgroupsRequest
	(*UpdateHostgroupsReply)(nil),   // 3: api.appix.v1.UpdateHostgroupsReply
	(*DeleteHostgroupsRequest)(nil), // 4: api.appix.v1.DeleteHostgroupsRequest
	(*DeleteHostgroupsReply)(nil),   // 5: api.appix.v1.DeleteHostgroupsReply
	(*GetHostgroupsRequest)(nil),    // 6: api.appix.v1.GetHostgroupsRequest
	(*GetHostgroupsReply)(nil),      // 7: api.appix.v1.GetHostgroupsReply
	(*ListHostgroupsRequest)(nil),   // 8: api.appix.v1.ListHostgroupsRequest
	(*ListHostgroupsReply)(nil),     // 9: api.appix.v1.ListHostgroupsReply
}
var file_appix_v1_hostgroups_proto_depIdxs = []int32{
	0, // 0: api.appix.v1.Hostgroups.CreateHostgroups:input_type -> api.appix.v1.CreateHostgroupsRequest
	2, // 1: api.appix.v1.Hostgroups.UpdateHostgroups:input_type -> api.appix.v1.UpdateHostgroupsRequest
	4, // 2: api.appix.v1.Hostgroups.DeleteHostgroups:input_type -> api.appix.v1.DeleteHostgroupsRequest
	6, // 3: api.appix.v1.Hostgroups.GetHostgroups:input_type -> api.appix.v1.GetHostgroupsRequest
	8, // 4: api.appix.v1.Hostgroups.ListHostgroups:input_type -> api.appix.v1.ListHostgroupsRequest
	1, // 5: api.appix.v1.Hostgroups.CreateHostgroups:output_type -> api.appix.v1.CreateHostgroupsReply
	3, // 6: api.appix.v1.Hostgroups.UpdateHostgroups:output_type -> api.appix.v1.UpdateHostgroupsReply
	5, // 7: api.appix.v1.Hostgroups.DeleteHostgroups:output_type -> api.appix.v1.DeleteHostgroupsReply
	7, // 8: api.appix.v1.Hostgroups.GetHostgroups:output_type -> api.appix.v1.GetHostgroupsReply
	9, // 9: api.appix.v1.Hostgroups.ListHostgroups:output_type -> api.appix.v1.ListHostgroupsReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_appix_v1_hostgroups_proto_init() }
func file_appix_v1_hostgroups_proto_init() {
	if File_appix_v1_hostgroups_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_appix_v1_hostgroups_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_appix_v1_hostgroups_proto_goTypes,
		DependencyIndexes: file_appix_v1_hostgroups_proto_depIdxs,
		MessageInfos:      file_appix_v1_hostgroups_proto_msgTypes,
	}.Build()
	File_appix_v1_hostgroups_proto = out.File
	file_appix_v1_hostgroups_proto_rawDesc = nil
	file_appix_v1_hostgroups_proto_goTypes = nil
	file_appix_v1_hostgroups_proto_depIdxs = nil
}
