// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.12.4
// source: appix/v1/teams.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTeamsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateTeamsRequest) Reset() {
	*x = CreateTeamsRequest{}
	mi := &file_appix_v1_teams_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamsRequest) ProtoMessage() {}

func (x *CreateTeamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appix_v1_teams_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamsRequest.ProtoReflect.Descriptor instead.
func (*CreateTeamsRequest) Descriptor() ([]byte, []int) {
	return file_appix_v1_teams_proto_rawDescGZIP(), []int{0}
}

type CreateTeamsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateTeamsReply) Reset() {
	*x = CreateTeamsReply{}
	mi := &file_appix_v1_teams_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamsReply) ProtoMessage() {}

func (x *CreateTeamsReply) ProtoReflect() protoreflect.Message {
	mi := &file_appix_v1_teams_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamsReply.ProtoReflect.Descriptor instead.
func (*CreateTeamsReply) Descriptor() ([]byte, []int) {
	return file_appix_v1_teams_proto_rawDescGZIP(), []int{1}
}

type UpdateTeamsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateTeamsRequest) Reset() {
	*x = UpdateTeamsRequest{}
	mi := &file_appix_v1_teams_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTeamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeamsRequest) ProtoMessage() {}

func (x *UpdateTeamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appix_v1_teams_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeamsRequest.ProtoReflect.Descriptor instead.
func (*UpdateTeamsRequest) Descriptor() ([]byte, []int) {
	return file_appix_v1_teams_proto_rawDescGZIP(), []int{2}
}

type UpdateTeamsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateTeamsReply) Reset() {
	*x = UpdateTeamsReply{}
	mi := &file_appix_v1_teams_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTeamsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeamsReply) ProtoMessage() {}

func (x *UpdateTeamsReply) ProtoReflect() protoreflect.Message {
	mi := &file_appix_v1_teams_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeamsReply.ProtoReflect.Descriptor instead.
func (*UpdateTeamsReply) Descriptor() ([]byte, []int) {
	return file_appix_v1_teams_proto_rawDescGZIP(), []int{3}
}

type DeleteTeamsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteTeamsRequest) Reset() {
	*x = DeleteTeamsRequest{}
	mi := &file_appix_v1_teams_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamsRequest) ProtoMessage() {}

func (x *DeleteTeamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appix_v1_teams_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeamsRequest.ProtoReflect.Descriptor instead.
func (*DeleteTeamsRequest) Descriptor() ([]byte, []int) {
	return file_appix_v1_teams_proto_rawDescGZIP(), []int{4}
}

type DeleteTeamsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteTeamsReply) Reset() {
	*x = DeleteTeamsReply{}
	mi := &file_appix_v1_teams_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeamsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamsReply) ProtoMessage() {}

func (x *DeleteTeamsReply) ProtoReflect() protoreflect.Message {
	mi := &file_appix_v1_teams_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeamsReply.ProtoReflect.Descriptor instead.
func (*DeleteTeamsReply) Descriptor() ([]byte, []int) {
	return file_appix_v1_teams_proto_rawDescGZIP(), []int{5}
}

type GetTeamsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetTeamsRequest) Reset() {
	*x = GetTeamsRequest{}
	mi := &file_appix_v1_teams_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamsRequest) ProtoMessage() {}

func (x *GetTeamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appix_v1_teams_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamsRequest.ProtoReflect.Descriptor instead.
func (*GetTeamsRequest) Descriptor() ([]byte, []int) {
	return file_appix_v1_teams_proto_rawDescGZIP(), []int{6}
}

type GetTeamsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetTeamsReply) Reset() {
	*x = GetTeamsReply{}
	mi := &file_appix_v1_teams_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamsReply) ProtoMessage() {}

func (x *GetTeamsReply) ProtoReflect() protoreflect.Message {
	mi := &file_appix_v1_teams_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamsReply.ProtoReflect.Descriptor instead.
func (*GetTeamsReply) Descriptor() ([]byte, []int) {
	return file_appix_v1_teams_proto_rawDescGZIP(), []int{7}
}

type ListTeamsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListTeamsRequest) Reset() {
	*x = ListTeamsRequest{}
	mi := &file_appix_v1_teams_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamsRequest) ProtoMessage() {}

func (x *ListTeamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appix_v1_teams_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamsRequest.ProtoReflect.Descriptor instead.
func (*ListTeamsRequest) Descriptor() ([]byte, []int) {
	return file_appix_v1_teams_proto_rawDescGZIP(), []int{8}
}

type ListTeamsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListTeamsReply) Reset() {
	*x = ListTeamsReply{}
	mi := &file_appix_v1_teams_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamsReply) ProtoMessage() {}

func (x *ListTeamsReply) ProtoReflect() protoreflect.Message {
	mi := &file_appix_v1_teams_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamsReply.ProtoReflect.Descriptor instead.
func (*ListTeamsReply) Descriptor() ([]byte, []int) {
	return file_appix_v1_teams_proto_rawDescGZIP(), []int{9}
}

var File_appix_v1_teams_proto protoreflect.FileDescriptor

var file_appix_v1_teams_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x70, 0x70, 0x69, 0x78, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x65, 0x61, 0x6d, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x69,
	0x78, 0x2e, 0x76, 0x31, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65,
	0x61, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x14,
	0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x65,
	0x61, 0x6d, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x12,
	0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x54, 0x65, 0x61, 0x6d,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x12, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x65,
	0x61, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x4c, 0x69,
	0x73, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x8d, 0x03, 0x0a,
	0x05, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x12, 0x4f, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x65, 0x61, 0x6d, 0x73, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x69,
	0x78, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70,
	0x70, 0x69, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61,
	0x6d, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4f, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x70,
	0x69, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61,
	0x70, 0x70, 0x69, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x65,
	0x61, 0x6d, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4f, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70,
	0x70, 0x69, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x65, 0x61,
	0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x61, 0x70, 0x70, 0x69, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54,
	0x65, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x46, 0x0a, 0x08, 0x47, 0x65, 0x74,
	0x54, 0x65, 0x61, 0x6d, 0x73, 0x12, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x69,
	0x78, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x69, 0x78,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x49, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x12, 0x1e,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x69, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x69, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x27, 0x0a, 0x0c,
	0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x69, 0x78, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x15,
	0x61, 0x70, 0x70, 0x69, 0x78, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x70, 0x69, 0x78, 0x2f,
	0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_appix_v1_teams_proto_rawDescOnce sync.Once
	file_appix_v1_teams_proto_rawDescData = file_appix_v1_teams_proto_rawDesc
)

func file_appix_v1_teams_proto_rawDescGZIP() []byte {
	file_appix_v1_teams_proto_rawDescOnce.Do(func() {
		file_appix_v1_teams_proto_rawDescData = protoimpl.X.CompressGZIP(file_appix_v1_teams_proto_rawDescData)
	})
	return file_appix_v1_teams_proto_rawDescData
}

var file_appix_v1_teams_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_appix_v1_teams_proto_goTypes = []any{
	(*CreateTeamsRequest)(nil), // 0: api.appix.v1.CreateTeamsRequest
	(*CreateTeamsReply)(nil),   // 1: api.appix.v1.CreateTeamsReply
	(*UpdateTeamsRequest)(nil), // 2: api.appix.v1.UpdateTeamsRequest
	(*UpdateTeamsReply)(nil),   // 3: api.appix.v1.UpdateTeamsReply
	(*DeleteTeamsRequest)(nil), // 4: api.appix.v1.DeleteTeamsRequest
	(*DeleteTeamsReply)(nil),   // 5: api.appix.v1.DeleteTeamsReply
	(*GetTeamsRequest)(nil),    // 6: api.appix.v1.GetTeamsRequest
	(*GetTeamsReply)(nil),      // 7: api.appix.v1.GetTeamsReply
	(*ListTeamsRequest)(nil),   // 8: api.appix.v1.ListTeamsRequest
	(*ListTeamsReply)(nil),     // 9: api.appix.v1.ListTeamsReply
}
var file_appix_v1_teams_proto_depIdxs = []int32{
	0, // 0: api.appix.v1.Teams.CreateTeams:input_type -> api.appix.v1.CreateTeamsRequest
	2, // 1: api.appix.v1.Teams.UpdateTeams:input_type -> api.appix.v1.UpdateTeamsRequest
	4, // 2: api.appix.v1.Teams.DeleteTeams:input_type -> api.appix.v1.DeleteTeamsRequest
	6, // 3: api.appix.v1.Teams.GetTeams:input_type -> api.appix.v1.GetTeamsRequest
	8, // 4: api.appix.v1.Teams.ListTeams:input_type -> api.appix.v1.ListTeamsRequest
	1, // 5: api.appix.v1.Teams.CreateTeams:output_type -> api.appix.v1.CreateTeamsReply
	3, // 6: api.appix.v1.Teams.UpdateTeams:output_type -> api.appix.v1.UpdateTeamsReply
	5, // 7: api.appix.v1.Teams.DeleteTeams:output_type -> api.appix.v1.DeleteTeamsReply
	7, // 8: api.appix.v1.Teams.GetTeams:output_type -> api.appix.v1.GetTeamsReply
	9, // 9: api.appix.v1.Teams.ListTeams:output_type -> api.appix.v1.ListTeamsReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_appix_v1_teams_proto_init() }
func file_appix_v1_teams_proto_init() {
	if File_appix_v1_teams_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_appix_v1_teams_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_appix_v1_teams_proto_goTypes,
		DependencyIndexes: file_appix_v1_teams_proto_depIdxs,
		MessageInfos:      file_appix_v1_teams_proto_msgTypes,
	}.Build()
	File_appix_v1_teams_proto = out.File
	file_appix_v1_teams_proto_rawDesc = nil
	file_appix_v1_teams_proto_goTypes = nil
	file_appix_v1_teams_proto_depIdxs = nil
}
