server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
  tracer: "gag"
data:
  database:
    driver: sqlite
    source: database/data.sqlite
admin:
  admin_password: admin@123
  strict_password_policy: true
  jwt_expire_hours: 1
  jwt_secret: "appix"
  emergency_header: "appix-emergency"
authz:
  model_file: "configs/rbac_model.conf"
